# Generated by Django 5.2.8 on 2025-11-22 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_totp_enabled_user_totp_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='recovery_keys',
            field=models.TextField(blank=True, null=True),
        ),
    ]
