# Generated by Django 5.2.8 on 2025-11-23 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_recovery_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='argon_memory',
            field=models.IntegerField(default=32768),
        ),
        migrations.AddField(
            model_name='user',
            name='argon_time',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='user',
            name='encrypted_master_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='master_key_nonce',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='master_key_salt',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
