# Generated by Django 5.2.8 on 2025-11-06 14:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('content', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('settings', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BlockNotebookConnector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.block')),
                ('notebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.notebook')),
            ],
            options={
                'unique_together': {('block', 'notebook')},
            },
        ),
        migrations.CreateModel(
            name='NotebookUserConnector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.notebook')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'notebook')},
            },
        ),
    ]
