# Generated by Django 5.2.8 on 2025-11-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blocknotebookconnector',
            name='position_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blocknotebookconnector',
            name='position_order',
            field=models.IntegerField(default=0),
        ),
    ]
