# Generated by Django 5.2.8 on 2025-11-22 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_blocknotebookconnector_position_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebookuserconnector',
            name='last_opened',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
